### ISSUE TITLE
feature request: how about multiple test suffixes?

### ISSUE THREAD

**Issue by BrianHicks** [juanedi/elm-test-runner#3]
Some Elm projects I work on use `Test` as a suffix, and some use `Spec`. It'd be nice if I could specify  this:

```elisp
(setq elm-test-runner-preferred-test-suffix '("Test" "Spec"))
```

I'm imagining that this would look for all the matching files when jumping to an alternative, and use the head of the list as the prefix when creating a missing file.

**Comment by juanedi** [comment]
Could this be solved by using [directory variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html)?

I can't test right now but am pretty sure that I made that worked before with a per-project `.dir-locals` file.

Let me know if that works!

**Comment by juanedi** [comment]
@BrianHicks can you confirm if directory variables solves your use case or if there's something I'm missing?

I'd like to avoid the library being smart about stuff to make the behavior easier to understand, specially when the problem seems to be easy to solve by a more standard mechanism.

(TBH, I'm even wondering if autodetecting the `elm-test` binary on `node_modules` was a good idea but I guess I'd rather not remove it if users already depend on it).
